config/routes.rb
FbPagetabBase::Application.routes.draw do
  resources :facebook, only: :create

  root to: 'welcome#index'

  controller :pages do
    get 'privacy_policy'
    get 'terms_of_service'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :user_id, :access_token, :first_name, :last_name, :email
  validates :email, format: { with: /\A\S+@\S+\.\S+\z/ }

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def profile_picture_url(width = 150, height = 150)
    graph.get_picture('me', width: width, height: height)
  end

  def friends
    # Returns an array of hashes in the format
    # { 'name' => '', 'id' => '' }
    @friends ||= graph.get_connection('me', 'friends').sort do |a, b|
      a['name'] <=> b['name']
    end
  end

  private

    def graph
      @graph ||= Koala::Facebook::API.new(access_token)
    end
end

app/models/user_service.rb
class UserService

  def initialize(user_id, oauth_token)
    @user_id = user_id
    @oauth_token = oauth_token
  end

  def update_or_create
    user = update_or_create!
  rescue => e
    Rails.logger.info e.message
    Rails.logger.info e.backtrace
  ensure
    user
  end

  private

    attr_accessor :user_id, :oauth_token

    def update_or_create!
      user = User.find_by(user_id: user_id)

      if user
        if user.access_token != oauth_token
          user.update!(access_token: oauth_token)
        end
      else
        graph = Koala::Facebook::API.new(oauth_token)
        profile = graph.get_object('me')

        user = User.create!(
          user_id: user_id,
          access_token: oauth_token,
          first_name: profile['first_name'],
          last_name: profile['last_name'],
          email: profile['email']
        )
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController

  helper_method :current_user

  skip_before_action :verify_authenticity_token, only: :create

  before_action :require_authentication, except: :create
  before_action :require_like, except: :create if ENV.key?('FAN_GATE')

  # The maximum number of times to allow the
  # user to attempt to login in one session
  MAX_LOGIN_ATTEMPTS = 2

  def create
    parsed_signed_request = request.env['facebook.parsed_signed_request']

    # Track whether or not the user likes the page
    session[:like] = parsed_signed_request['page']['liked']

    if parsed_signed_request.key?('user_id')
      # Your app is authorized
      # See https://developers.facebook.com/docs/appsonfacebook/tutorial/#auth

      user_id = parsed_signed_request['user_id']

      if UserService.new(user_id, parsed_signed_request['oauth_token']).update_or_create
        session[:user_id] = user_id
        redirect_to root_url
      else
        render status: :internal_server_error, text: "Sorry for the inconvenience! Your user account could not be accessed at this time. Please try again at a later time. If the problem persists then you can try contacting the page's administrator for immediate assistance."
      end
    elsif session[:login_attempts] == MAX_LOGIN_ATTEMPTS
      # For some reason params[:error_reason] was not being set to 'user_denied'
      # so I decided to track the number of login_attempts instead
      # See https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#nonjscancel
      session[:login_attempts] = nil

      render inline: "<script>window.top.location = 'https://www.facebook.com/pages/null/#{parsed_signed_request['page']['id']}';</script>"
    else
      # Pass the user through an authentication flow
      # Redirect to OAuth Dialog
      session[:login_attempts] = session[:login_attempts].to_i + 1

      render inline: %Q{
        <script>
          var oauth_url = 'https://www.facebook.com/dialog/oauth/';
          oauth_url += '?client_id=#{ENV['FACEBOOK_APP_ID']}';
          oauth_url += '&redirect_uri=' + encodeURIComponent('https://www.facebook.com/pages/null/#{parsed_signed_request['page']['id']}/?sk=app_#{ENV['FACEBOOK_APP_ID']}');
          oauth_url += '&scope=#{ENV['FACEBOOK_SCOPE']}';

          window.top.location = oauth_url;
        </script>
      }
    end
  end

  private

    def require_like
      render 'facebook/like_gate' unless session[:like]
    end

    def require_authentication
      render status: :bad_request, text: 'You must login through Facebook in order to use this application.' unless logged_in?
    end

    def logged_in?
      current_user != nil
    end

    def current_user
      @current_user ||= User.find_by(user_id: session[:user_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < FacebookController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def host
    request.env['HTTP_HOST']
  end

  def url_no_scheme(path = '')
    "//#{host}#{path}"
  end
end

app/views/facebook/like_gate.html.erb
<p>You must like the page to continue.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- Ensure proper rendering and touch zooming on mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>Facebook Page Tab Base</title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/fb_init' %>

    <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/privacy_policy.html.erb
<h1>Privacy Policy</h1>

app/views/pages/terms_of_service.html.erb
<h1>Terms of Service</h1>

app/views/shared/_fb_init.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : "<%= ENV['FACEBOOK_APP_ID'] %>",
      channelUrl : "<%= url_no_scheme('/channel.html') %>",
      status     : true,
      xfbml      : true
    });

    FB.Canvas.setAutoGrow();

    // Additional initialization code
    <%= yield :fb_init %>
  };

  // Load the SDK asynchronously
  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <ul class="main-footer-app-links">
    <li><%= link_to 'Home', root_path %></li>
  </ul>
  <ul class="main-footer-required-links">
    <li><%= link_to 'Privacy Policy', privacy_policy_path %></li>
    <li><%= link_to 'Terms of Service', terms_of_service_path %></li>
  </ul>
</footer>

app/views/welcome/index.html.erb
<p>Hello, <%= current_user.full_name %>.</p>

<p>
  <%= image_tag current_user.profile_picture_url, alt: "Profile picture of #{current_user.full_name}" %>
</p>

<p>
  You have <%= pluralize(current_user.friends.size, 'friend') %>:
</p>

<ul>
  <% current_user.friends.each do |friend| %>
    <li>
      <%= link_to friend['name'], "https://www.facebook.com/#{friend['id']}", target: '_blank' %>
    </li>
  <% end %>
</ul>